# Site wide configuration

title: Opiate for the masses
locale: en_US
description: Data is our religion. 
logo: 
search: true
disqus-shortname: opiateforthemasses 
#url: http://quiri.github.io

# Jekyll configuration
encoding: utf-8
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Kirill Pomogajko
  avatar: kirill.jpg
  email: kirill@pomogajko.com
  twitter: pomogajko
  #facebook: #username
  github: Quiri
  #stackexchange: #http://stackoverflow.com/users/123456/username
  #linkedin: #username
  #instagram: #username
  #flickr: #username
  #tumblr: #username
  #pinterest: #username
  #weibo: #userid
  google:
  #  plus: #username
    analytics: UA-66397956-1
    verify: MmRGCeK6NxYVbxHuKT7FP5H40y1L-DnHXuVMKbRfBwQ
  #  ad-client:
  #  ad-slot:
  #bing-verify:
